language: rust
services:
  - docker
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt -- --check
  - cargo build --verbose
  - cargo test --verbose
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
  fast_finish: true
cache: cargo