language: rust
services:
  - docker
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose --features container
  - cargo test --verbose --features container
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo