[package]
name = "chesterfield"
version = "0.1.0"
authors = ["Daniel Eades <danieleades@hotmail.com>"]
edition = "2018"
license = "apache-2.0"

[badges]
travis-ci = { repository = "danieleades/chesterfield" }

[dependencies]
serde = {version= "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
reqwest = "0.9.16"

[build-dependencies]
cargo-readme = "3.1.2"